### ISSUE TITLE
Ability to change the "PiKVM" prefix for devices

### ISSUE THREAD

**Issue by kkeker** [pikvm/pikvm#1008]
**Is your feature request related to a problem? Please describe.**
I can't change the device names that PiKVM appears to be. From Bluetooth HID PiKVM mouse/keyboard devices to USB CDROM, HDMI monitor, etc. We are talking about the devices that PiKVM appears to be when connected via USB or Bluetooth. I saw that this name is a hardcode in the `pikvmd` library.

**Describe the solution you'd like**
Add to the configuration file `/etc/kvmd/override.yaml` the ability to force the name of each device into the configuration sections of these devices. Especially relevant for Bluetooth HID https://docs.pikvm.org/bluetooth_hid/#using-bluetooth-hid .

Something like this:
```
kvmd:
    hid:
        type: bt
        name: 'New BT HID Name'
```
or
```
otg:
    devices:
        drives:
            enabled: true
            default:
                cdrom: true
                name: 'New CDROM Name'
```

**Describe alternatives you've considered**
Any other option would also be acceptable.

**Additional context**
In the case of the Bluetooth HID, I found a file that creates `kvmd` at startup, there is a device name there, and tried to write a systemd unit-file to rename the Bluetooth device after starting `kvmd` and then cause an overload of the Bluetooth service. But this option does not work, the Bluetooth device is no longer visible in the search for other devices.

**Comment by mdevaev** [comment]
This will work:
```yaml
kvmd:
    hid:
        type: bt
        manufacturer: PiKVM
        product: "HID Device"
        description "Bluetooth Keyboard & Mouse"
```
See `kvmd -m` for other options.
