### ISSUE TITLE
The OTG keyboard does not work after HID Reset

### ISSUE THREAD

**Issue by kkeker** [pikvm/pikvm#1044]
**Describe the bug**
I performed HID Reset in KVMD WebUI after that my keyboard does not work, including WebUI Screen/Software Keyboard, VNC, WebUI Hardware Keyboard.

**To Reproduce**
Steps to reproduce the behavior, like:
1. Open the WebUI KVM interface
2. Select from the menu at the top right HID Reset
3. Your keyboard will not work

**Desktop (please complete the following information):**
 - Any Web Browser
 - Any VNC Client
 - Any Hardware Keyboard (through the WebUI)
 - Screen/Software Keyboard (KVMD WebUI)

**PiKVM info:**
  - Raspberry Pi Zero 2w
  - PiKVM platform v2-hdmi
  - Video capture type CSI bridge
  - KVMD version:
		kvmd 3.231-1
		kvmd-fan 0.26-1
		kvmd-oled 0.23-1
		kvmd-platform-v2-hdmi-zero2w 3.231-1
		kvmd-webterm 0.43-1
  - uStreamer version: ustreamer 5.41-1
  - Linux kernel: Linux device 5.15.68-3-rpi-ARCH

**Additional context**
Of course, I tried to disconnect storage devices that seem to be pikvm through the OTG port, I read about this problem, but it didn't help me. Also, I tried disabling different configuration sections related to OTG, Serial, OTG net, HID and this did not help.

***override.yaml***
```
vnc:
    keymap: /usr/share/kvmd/keymaps/ru
    auth:
        vncauth:
            enabled: true
server:
    host: device

kvmd:
    ocr:
        langs:
            - eng
            - rus
    atx:
        type: disabled
    msd:
        type: disabled
    hid:
        mouse_alt:
            device: /dev/kvmd-hid-mouse-alt

otg:
    manufacturer: LG
    product: LG Generic Device
    devices:
        serial:
            enabled: false
        drives:
            enabled: false
        ethernet:
            enabled: false
```
