### ISSUE TITLE
The user choice for the 'jiggler' option isn't persistent

### ISSUE THREAD

**Issue by yurivict** [pikvm/pikvm#1205]
**Describe the bug**
The setting kvm.hid.jiggler enables the user to toggle this option.
However, there is a problem:
The user's choice for the jiggler option isn't persistent across reboots.

Every time when the system reboots the user needs to set this value again which is a hassle.

The other option choices might have the same problem.

**Comment by mdevaev** [comment]
Many options were not planned to be persistent. As for jiggler, you can make it enabled by default:

```yaml
kvmd:
    hid:
        jiggler:
            enabled: true
            active: true
```
