### ISSUE TITLE
Please add the ability to have user defined text on the KVM screen

### ISSUE THREAD

**Issue by CWwwKr** [pikvm/pikvm#1207]
It would be extremely helpful if text could be added to the top of the two windows and on the sides of the KVM screens. This would be very helpful for management and maintenance of a large number of computers / servers that have different requirements to get into the BIOS and boot menus.  Some PCs use F2 to enter the BIOS screen.  Others use “ESC”.    I have a small fleet of PiKVM v4 Plus and this would be a large help to keep things straight for each computer.

It would make management and maintenance of servers/PCs a lot simpler to be able to put HTML into a file and have it displayed on the screen in a manner that calls your attention to it.  If possible, with CSS – but being able to put the text in red would be great if that is all that is possible.

This could be data in a .yaml file with 4 sections to cover the four arrows in the attached  screen shot

![image](https://github.com/pikvm/pikvm/assets/30428410/3d8eacf0-2c23-4f98-9e59-37be3c70ba76)

**Comment by mdevaev** [comment]
I've added left and right columns configurable via meta.yaml like this:

```yaml
server:
    host: localhost.localdomain

kvm: {}

tips:
    left: test left
    right: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.


Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
```

![image](https://github.com/user-attachments/assets/7ef0c496-e74d-4821-881b-6e2acd58eaab)

You can also change a visual style via `/etc/kvmd/web.css`:
```css
#kvmd-meta-tips-right {
        color: red;
}
```

I did not make the text in the navbar and window header because I want to leave this space reserved for future changes.

It will be available in the next release.
