### ISSUE TITLE
xh_hk4401 GUI not switching

### ISSUE THREAD

**Issue by iLLiac4** [pikvm/pikvm#1240]
Hi. 
Am using KVM switch xh_hk4401 and configured the FTDI serial adapter with inverted signals. When entering commands belov in terminal the ports are switching.
echo "SW1\r\nG01gA" > /dev/ttyUSB0
echo "SW2\r\nG02gA" > /dev/ttyUSB0
echo "SW3\r\nG03gA" > /dev/ttyUSB0
echo "SW3\r\nG03gA" > /dev/ttyUSB0

But GPIO on the interface GUI does not work. Have followed this guide https://docs.pikvm.org/xh_hk4401/#adding-ui-elements-to-control-the-kvm-switch with editing /etc/kvmd/override.yaml like described and it does not work over interface.
Same issue is described here:
https://github.com/ThomasVon2021/blikvm/issues/132

TNX

**Comment by iLLiac4** [comment]
Hi. I have found the fix and it works now.

Edit file /etc/kvmd/override.yaml and add the line:
protocol: 2

Sample:

```
kvmd:
    gpio:
        drivers:
            hk:
                type: xh_hk4401
                protocol: 2
                device: /dev/ttyUSB0
        scheme:
            ch0_led:
                driver: hk
```
