### ISSUE TITLE
500 Internal Server Error after modifying override.yaml

### ISSUE THREAD

**Issue by deanfourie1** [pikvm/pikvm#1449]
**Describe the bug**
So I know this is probably down to an issue with the override.yaml file, but i've literally formatted it exactly as per the documentation and used a proper code formatter to edit. Still, it does not boot when using the code in override.yaml

**To Reproduce**
Steps to reproduce the behavior, like:
1. Edit the override.yaml with the code below.
2. Reboot PiKVM
3. When attempting to access the webUI, I get error 500, Internal Server Error

**Expected behavior**
The webUI to load.

**Screenshots**

**Desktop (please complete the following information):**
 - VNC client (if used)

**PiKVM info:**
  - Raspberry Pi board version [e.g. RPi 4]: Rpi 4B
  - PiKVM platform [e.g. v2-hdmi]: V2
  - Video capture type [e.g. CSI bridge]: USB
  - KVMD version: `pacman -Q | grep kvmd`
```
  kvmd 4.10-1
kvmd-fan 0.31-1
kvmd-oled 0.27-1
kvmd-platform-v2-hdmiusb-rpi4 4.10-1
kvmd-webterm 0.50-1
```
  - uStreamer version: `pacman -Q | grep ustreamer`: ustreamer 6.14-1
  - Linux kernel: `uname -a`: Linux pikvm 6.6.45-7-rpi #1 SMP Mon Sep  2 09:16:27 UTC 2024 armv7l GNU/Linux

**Additional context**
This is the override.yaml used.

```
kvmd:
    gpio:
        scheme:
            button1:
                pin: 25
                mode: output
                switch: false
            button2:
                pin: 24
                mode: output
                switch: false
            button3:
                pin: 5
                mode: output
                switch: false
            button4:
                pin: 16
                mode: output
                switch: false
            button5:
                pin: 13
                mode: output
                switch: false
            button6:
                pin: 21
                mode: output
                switch: false
            button7:
                pin: 4
                mode: output
                switch: false
            button8:
                pin: 27
                mode: output
                switch: false

        view:
            header:
                title: Input Select
            table:
                - ["#Inputs"]
                - []
                - ["#Input 1:", button1]
                - ["#Input 2:", button2]
                - ["#Input 3:", button3]
                - ["#Input 4:", button4]
            header:
                title: Reboot
            table:
                - ["#Reboot"]
                - []
                - ["#Reboot 1:", button5]
                - ["#Reboot 2:", button6]
                - ["#Reboot 3:", button7]
                - ["#Reboot 4:", button8]
```
