### ISSUE TITLE
Keystrokes sent repeatedly all the time

### ISSUE THREAD

**Issue by Simon1511** [pikvm/pikvm#1463]
**Describe the bug**
Pressing any key on the keyboard in the Web UI will make it "spam" that key for around 1-2 seconds. So for example, when I try to log in as "root" in a shell, I'll end up with "rrrrrrrrrrrrrrrrrrrooooooottttt". I already tried enabling the recently added "Bad link mode" in the PiKVM UI, but that does not fix the issue at all. In fact it makes it worse because both the physical and virtual keyboard will eventually just stop accepting any key input until I switch the inputs of my KVM-Switch (ezcoo EZ-SW41H21-KVMU3P) and then switch back (I guess this is equivalent to unplugging USB from the physical machine?).

**To Reproduce**
1. Plug a PC into the PiKVM (HDMI + USB-A to USB-A cable)
2. Open the PiKVM Web UI
3. Try to type anything and it'll "spam" that key with no way of interrupting it.

**Expected behavior**
Any text should be written as normal, it should only output what I'm actually typing instead of repeating it.

**Screenshots**
//

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 134
 - VNC client: none

**PiKVM info:**
  - Raspberry Pi board version: RPI 4b
  - PiKVM platform: /
  - Video capture type: CSI bridge
  - KVMD version: 4.43-1
  - uStreamer version: 6.23-1
  - Linux kernel: Linux pikvm 6.6.45-9-rpi

**Additional context**
I'm using the ezcoo EZ-SW41H21-KVMU3P KVM-Switch with my PiKVM. Not sure if that's related to the issue.

**Comment by Simon1511** [comment]
Seems like none of my devices like PiKVM's mouse? Once I added keybord, mouse and MSD to override.yml and toggled off mouse in the Web UI it started to work perfectly fine, no more repeated key presses.

Perhaps someone knows why specifically the mouse triggers this?

**Comment by mdevaev** [comment]
What the host device do you use?

**Comment by Simon1511** [comment]
> What the host device do you use?

Multiple different hosts, happens with all of them:
- Fujitsu Q556
- Fujitsu S920
- Dell OptiPlex 7040M
- some noname chinese Mini-PC

**Comment by mdevaev** [comment]
Please check the following:
* Will this bug be reproduced without ezcoo, just with direct pikvm->host connection?
* Please try other browser, like chrome without any extensions and even in incognito mode.

**Comment by mdevaev** [comment]
Sup?

**Comment by Simon1511** [comment]
> Please check the following:
> 
>     * Will this bug be reproduced without ezcoo, just with direct pikvm->host connection?
> 
>     * Please try other browser, like chrome without any extensions and even in incognito mode.

Sorry for the long delay on this, been pretty busy with other stuff the past week.

I just tried what you suggested, and in fact that issue does not happen at all with direct PiKVM to Host connection, regardless of the browser used.

With the Ezcoo connected I tried Firefox and Edge, both have the issue.

On a side note: with the PiKVM's USB plugged into the MOUSE port of the Ezcoo, the keyboard will function correctly, however the mouse will stop working and switching between inputs is not possible.
With it plugged into the KEYBOARD port on the Ezcoo, all works but said issue happens (and goes away once I turn off the mouse in PiKVM).

**Comment by mdevaev** [comment]
Okay, this is Ezcoo problem, it can't be solved on our side. Apparently, their USB driver inside the device does not handle mouse events correctly.

I would recommend that you use a cable and configure port switching from PiKVM: http://docs.pikvm.org/ezcoo

**Comment by Simon1511** [comment]
> Okay, this is Ezcoo problem, it can't be solved on our side. Apparently, their USB driver inside the device does not handle mouse events correctly.
> 
> I would recommend that you use a cable and configure port switching from PiKVM: http://docs.pikvm.org/ezcoo

This specific Ezcoo switch does not have a dedicated control port though. I got it for cheap because it's listed as "Everything is working as expected" on the [PiKVM Docs](https://docs.pikvm.org/multiport/#list-of-tested-third-party-kvms):

![Image](https://github.com/user-attachments/assets/b888e011-f16c-4722-8640-29c48aba2e12)

 Apparently that's not the case. You might want to add something like "Mouse input broken" to the Docs then.

On a side note though: Would it be possible to split the PiKVM's USB output into two cables, one for keyboard + MST and one for mouse? Maybe even with an Arduino or something in between?

I also wonder if it would help to modify the HID devices that PiKVM outputs? Currently it seems to be detected as "Microsoft-KM-v1.a".

**Comment by mdevaev** [comment]
> Apparently that's not the case. You might want to add something like "Need to disable Mouse input in PiKVM" to the Docs then.

We have not been informed of any problems before. Maybe Ezcoo has updated the firmware, or vice versa, your firmware is too old.

> On a side note though: Would it be possible to split the PiKVM's USB output into two cables, one for keyboard + MSD and one for mouse?

No. But I was thinking, what happens if you disable MSD? Would it work better with just a keyboard and mouse?

> I also wonder if it would help to modify the HID devices that PiKVM outputs?

It will not help. PiKVM HID is already configured for maximum compatibility. You can only try disabling horizontal scrolling and double mouse: https://docs.pikvm.org/mouse

**Comment by Simon1511** [comment]
> No. But I was thinking, what happens if you disable MSD? Would it work better with just a keyboard and mouse?

Disabling MSD has no effect, it will continue to repeat the keys even with it disabled.

> It will not help. PiKVM HID is already configured for maximum compatibility. You can only try disabling horizontal scrolling and double mouse: https://docs.pikvm.org/mouse

I already tried the dual mode thing but unfortunately having both enabled does not help, I need to have both relative and absolute mouse disabled to fix that issue:

![Image](https://github.com/user-attachments/assets/75f03f6f-dfd8-4e7e-a10d-f376bbdc1cee)

This is my override.yaml, not sure if this is fully correct:

```
kvmd:
    hid:
        mouse:
            absolute: false
            horizontal_wheel: false
        mouse_alt:
            device: /dev/kvmd-hid-mouse-alt
    gpio:
        drivers:
            otgconf:
                type: otgconf
        scheme:
            hid.usb0:
                driver: otgconf
                mode: output
                pin: hid.usb0
                pulse: false
            hid.usb1:
                driver: otgconf
                mode: output
                pin: hid.usb1
                pulse: false
            hid.usb2:
                driver: otgconf
                mode: output
                pin: hid.usb2
                pulse: false
            mass_storage.usb0:
                driver: otgconf
                mode: output
                pin: mass_storage.usb0
                pulse: false
        view:
            table:
                - ['#Keyboard', '#hid.usb0', hid.usb0]
                - ['#Absolute Mouse', '#hid.usb1', hid.usb1]
                - ['#Relative Mouse', '#hid.usb2', hid.usb2]
                - ['#Mass Storage Drive', '#mass_storage.usb0', mass_storage.usb0]
```

**Comment by mdevaev** [comment]
> Do you possibly know if it's possible to check what firmware version mine is running or something? Or do you know others with this specific KVM-Switch that I could ask for help?

No, I don't know. @arch1mede do you know someone? Or maybe do you have this switch?

To be honest, if I were you, I would return it and replace it for an Ezcoo with a control port.

**Comment by Simon1511** [comment]
> To be honest, if I were you, I would return it and replace it for an Ezcoo with a control port.

Unfortunately bought it used from Kleinanzeigen (German counterpart of Facebook Marketplace) for 90€. I don't really need the mouse that often as my hosts are all terminal only, so it's not much of a big deal. I'll keep my eyes open for some good offer on another Ezcoo one, or even the official PiKVM switch ;)

Thanks a lot for your help though, I'll see if I can play around with it a little more and will eventually get back here if I ever figure something out.

**Comment by mdevaev** [comment]
I'm sorry that I couldn't solve your problem. I remembered that we have an old patch that allowed us to use otg and arduino (now the pico) hid at the same time. But it doesn't accept the upstream and it takes a lot to adapt it to make it work. So yes, another switch would be the easiest solution.

**Comment by Simon1511** [comment]
> By the way, can you solder? If so, I have a tricky but working option for you.

Don't have a soldering iron here at the moment and my soldering skills aren't great but I might still try whatever your suggestion is ;)

**Comment by mdevaev** [comment]
In short, you can take several optocouplers and resistors and solder them to the Ezcoo board so that they close the switching buttons. Then connect the optocoupler with a resistor to the GPIO. The circuit is identical to ATX, just select unused pins.

**Comment by Simon1511** [comment]
Yeah that sounds way too advanced for me 😂

Thanks for the suggestion though.

**Comment by mdevaev** [comment]
At least I tried :D

Okay, then I'm closing this issue. If you have any new info, you can let me know and I will reopen it if necessary.

**Comment by tristan-k** [comment]
@Simon1511 Sorry for reopening the topic but I would like to know which features dont work with the ezcoo [EZ-SW41H21-KVMU3P 8K 4x1 switch](https://www.amazon.de/Computer-Tastatur-HDCP2-2-Fernbedienung-Kabelx4/dp/B0F4R9X7VG)? It's one of the few compatible HDMI 2.1 KVMs which are relative affordable in Germany. Is it just mouse support? Does switching the HDMI inputs still work?

**Comment by Simon1511** [comment]
> [@Simon1511](https://github.com/Simon1511) Sorry for reopening the topic but I would like to know which features dont work with the ezcoo [EZ-SW41H21-KVMU3P 8K 4x1 switch](https://www.amazon.de/Computer-Tastatur-HDCP2-2-Fernbedienung-Kabelx4/dp/B0F4R9X7VG)? It's one of the few compatible HDMI 2.1 KVMs which are relative affordable in Germany. Is it just mouse support? Does switching the HDMI inputs still work?

Switching the HDMI inputs works fine, though sometimes after switching it doesn't pick up the input correctly. But that can be fixed by hitting CTRL + CTRL + ESC once after switching to "reset" the HID on the KVM.

Mouse support however is completely borked with that KVM for me. As said earlier in this thread it might just be an issue with some models having a newer firmware or something.

However: Keyboard input will be completely broken unless you disable mouse input completely using the GPIO menu. If you keep the mouse enabled any keyboard input will end up being "delayed" and repeated (for example: press the M key -> nothing happens -> press again -> wait -> it repeadetly prints out "M" unless you press another key -> whole thing repeats from the start).
The GPIO menu can be enabled by adding the following to your /etc/kvmd/override.yml:

```
kvmd:
    hid:
        mouse:
            absolute: false
            horizontal_wheel: false
        mouse_alt:
            device: /dev/kvmd-hid-mouse-alt
    gpio:
        drivers:
            otgconf:
                type: otgconf
        scheme:
            hid.usb0:
                driver: otgconf
                mode: output
                pin: hid.usb0
                pulse: false
            hid.usb1:
                driver: otgconf
                mode: output
                pin: hid.usb1
                pulse: false
            hid.usb2:
                driver: otgconf
                mode: output
                pin: hid.usb2
                pulse: false
            mass_storage.usb0:
                driver: otgconf
                mode: output
                pin: mass_storage.usb0
                pulse: false
        view:
            table:
                - ['#Keyboard', '#hid.usb0', hid.usb0]
                - ['#Absolute Mouse', '#hid.usb1', hid.usb1]
                - ['#Relative Mouse', '#hid.usb2', hid.usb2]
                - ['#Mass Storage Drive', '#mass_storage.usb0', mass_storage.usb0]
```

That will give you the opportunity to disable Absolute and Relative mouse via the GUI:

<img width="737" height="365" alt="Image" src="https://github.com/user-attachments/assets/2a252d60-6a36-4d95-b0bd-670adc31e8c3" />

After doing that the keyboard will work as normal, but mouse will be completely disabled of course. Note that, after rebooting the PiKVM, it automatically switches both settings back to "On".

**Comment by Simon1511** [comment]
About half a year later and it seems like I have finally found a better solution to this issue.

So, to conclude what I previously experienced (all in combination with the Ezcoo):

- Mouse did not work
- Keystrokes sent repeatedly all the time
- Toggling Absolute and Relative Mouse off fixed the keystroke issue but of course disabled the mouse

I was randomly playing around with the settings and just noticed that the following fixes it:

1. Edit your kvm override.yml like in my previous post
2. Toggle off Relative Mouse and Mass Storage
3. <img width="616" height="377" alt="Image" src="https://github.com/user-attachments/assets/d3b915f9-d1a7-4e7b-bf60-025e6ecb095f" />
4. In the PiKVM settings, set Mouse to "Relative" (yes, this sounds like it makes no sense, but keep reading)
5. <img width="746" height="968" alt="Image" src="https://github.com/user-attachments/assets/3ffac5eb-3a7b-4d31-8272-9b6cbb6c6861" />
6. Hit "Reset HID"
7. Connect the PiKVM/Ezcoo to a host and magically, both the mouse and keyboard work normally

I have no idea why this works. Disabling Relative Mouse but then still telling the PiKVM to use it sounds stupid but it perfectly fixes the issues I was having.
For some reason Mass Storage needs to be disabled too, otherwise I could not get ANY keyboard or mouse input working. Once that's disabled, mouse and keyboard started working.

Maybe someone has an idea why this works and how it could be simplified? Maybe even a direct fix in PiKVM would be possible?

For now I've only tested this with a Windows laptop (Framework Laptop 13), but will later on check on some Linux hosts (Proxmox to be specific).

**Comment by mdevaev** [comment]
If you still use a swtch between pikvm and your target host, it would be the switch bug. I cant handle too complex usb device.

**Comment by Simon1511** [comment]
Yeah, seems so. Maybe this should be noted in the PiKVM Docs. This exact KVM switch model is still listed as "Everything works as expected" (which is obviously not the case anymore; or there are different revisions or firmware versions):

<img width="1468" height="221" alt="Image" src="https://github.com/user-attachments/assets/729c4b58-4851-4f6d-a852-63bc7d284ddd" />

**Comment by mdevaev** [comment]
May I ask you for PR? I think the reason is firmware.

**Comment by Simon1511** [comment]
Just for anyone else coming across this issue with the _**Ezcoo EZ-SW41H21-KVMU3P**_.

This is the `/etc/kvmd/override.yaml` that I ended up with. Note that this disables the PiKVM's MSD and absolute mouse. With those disabled and relative mouse enabled both keyboard and mouse are usable now.

```
otg:
    devices:
        hid:
            mouse_alt:
                start: false
        msd:
            start: false

kvmd:
    hid:
        keymap: /usr/share/kvmd/keymaps/de
        mouse:
            absolute: false
            horizontal_wheel: false
        mouse_alt:
            device: ""
```

PR will follow in a bit.
