### ISSUE TITLE
Unable to update due to pacman error - cannot read db extra

### ISSUE THREAD

**Issue by Majestic7979** [pikvm/pikvm#1490]
pikvm-update
+ trap on_error ERR
+ _yes='--noconfirm --ask=4 --overwrite \*'
+ rw
+ mount -o remount,rw /
+ mount -o remount,rw /boot
+ set +x
=== PiKVM is in Read-Write mode ===
+ pacman -Syy
:: Synchronizing package databases...
 core                                                                   238.9 KiB   405 KiB/s 00:01 [###########################################################] 100%
 extra                                                                    9.3 MiB  16.1 MiB/s 00:01 [###########################################################] 100%
 community                                                               45.0   B   900   B/s 00:00 [###########################################################] 100%
 alarm                                                                   95.7 KiB  1063 KiB/s 00:00 [###########################################################] 100%
 aur                                                                     11.1 KiB   185 KiB/s 00:00 [###########################################################] 100%
 pikvm                                                                   11.6 KiB  33.2 KiB/s 00:00 [###########################################################] 100%
error: failed retrieving file 'core.db' from mirror.osbeck.com : The requested URL returned error: 404
error: failed retrieving file 'extra.db' from mirror.osbeck.com : The requested URL returned error: 404
error: failed retrieving file 'community.db' from mirror.osbeck.com : The requested URL returned error: 404
warning: too many errors from mirror.osbeck.com, skipping for the remainder of this transaction
++ pacman -S -u --print-format %n
++ grep -v pikvm-os-updater
++ wc -l
error: could not read db 'extra' (Damaged tar archive (bad header checksum))
error: could not read db 'extra' (Damaged tar archive (bad header checksum))
error: could not read db 'extra' (Damaged tar archive (bad header checksum))
error: could not read db 'extra' (Damaged tar archive (bad header checksum))
error: could not read db 'extra' (Damaged tar archive (bad header checksum))
error: could not read db 'extra' (Damaged tar archive (bad header checksum))
error: could not read db 'extra' (Damaged tar archive (bad header checksum))
error: could not read db 'extra' (Damaged tar archive (bad header checksum))
error: could not read db 'extra' (Damaged tar archive (bad header checksum))
error: could not read db 'extra' (Damaged tar archive (bad header checksum))
error: could not read db 'extra' (Damaged tar archive (bad header checksum))
error: could not read db 'extra' (Damaged tar archive (bad header checksum))
error: could not read db 'extra' (Damaged tar archive (bad header checksum))
error: could not read db 'extra' (Damaged tar archive (bad header checksum))

**Comment by mdevaev** [comment]
Hello! Here the solution:
```
rw
pacman -U https://files.pikvm.org/tmp/libarchive-3.7.7-1-armv7h.pkg.tar.xz
pikvm-update
```

**Comment by Majestic7979** [comment]
Thank you, it's fixed.

While you're here, if you don't mind Maxim, I need to ask your advice please.

I purchased this item:
https://www.aliexpress.com/item/1005006209126315.html?spm=a2g0o.order_list.order_list_main.11.12141802lDXoxI

I wired the NO contact and the COMMON contact to a switch in a normal KVM, this KVM has a button in front of it that when clicked, switches between input 1 and input 2, so I just soldered wires to the contacts and when the wires are shorted for a moment the KVM switches between the inputs. So I tried to follow the guide on pikvm.org for optocoupler (https://docs.pikvm.org/gpio/) using GPIO but it's not switching... could you please kindly advice/walk me through? Here's my override currently:

```
kvmd:
    hid:
        jiggler:
            enabled: true
            active: true
    gpio:
        drivers:
            otgconf:
                type: otgconf
            relay:
                type: hidrelay
                device: /dev/hidg0  # The path to the linux device
        scheme:
            relay1:  # Channel 1 of the relay /dev/hidraw0
                driver: relay  # Not GPIO, so add name from the above Drivers section
                pin: 0  # Numerating starts from 0
                mode: output  # Relays can't be inputs
                switch: false
                #initial: null  # Don't reset the state to 0 when initializing and terminating KVMD
                pulse:
                    delay: 0.5  # Default pulse value
                    max_delay: 0.5  # The pulse interval can be between min_delay=0.1 (by default) and max_delay=2
            hid.usb0:
                driver: otgconf
                mode: output
                pin: hid.usb0
                pulse: false
            hid.usb1:
                driver: otgconf
                mode: output
                pin: hid.usb1
                pulse: false
            mass_storage.usb0:
                driver: otgconf
                mode: output
                pin: mass_storage.usb0
                pulse: false
        view:
            header:
                title: Functions
            table:
                - []
                - ["#KVM 1/2:", "relay1|Switch Machine"]  # Text label, one input, one button with text "Click"
                - []
                - ['#Keyboard', '#hid.usb0', hid.usb0]
                - ['#Absolute Mouse', '#hid.usb1', hid.usb1]
                - ['#Mass Storage Drive', '#mass_storage.usb0', mass_storage.usb0]
 ```
