### ISSUE TITLE
GPIO Pulse Does Not Return to Initial State for Active-Low Relay in PiKVM

### ISSUE THREAD

**Issue by radu-boboc** [pikvm/pikvm#1493]
**Describe the bug**

When using the GPIO configuration in PiKVM to control an active-low relay, the relay does not return to its initial state (HIGH, relay off) after a pulse is triggered. Instead, after the first click on the "Button" or "Pulse" element in the web interface, the relay remains activated (pin stays LOW, relay on). Subsequent clicks trigger a pulse that temporarily deactivates the relay (pin goes HIGH), but then the relay reactivates (pin returns to LOW). The expected behavior is for the relay to activate temporarily (pin goes LOW) and then return to its initial state (pin HIGH, relay off) after each click.

**To Reproduce**

Configure the GPIO in /etc/kvmd/override.yaml as follows:
```yaml
kvmd:
  gpio:
    drivers:
      atx:
        type: gpio
        pins:
    scheme:
      relay_1:
        driver: atx
        pin: 5
        mode: output
        initial: true
        invert: true
        switch: false
        pulse:
          delay: 0.2
          active: false
    view:
      header:
        title: Control ATX
      table:
        - ["#Reset Relay1", "relay_1", "Button"]
```

Restart the PiKVM service:
systemctl restart kvmd

Open the PiKVM web interface and go to the "Control ATX" menu.
Click on the "Reset Relay1" button.
Observe that the relay activates (pin goes LOW) but does not return to HIGH (relay remains on).
Click the button again, and observe that the relay deactivates temporarily (pin goes HIGH for 0.2 seconds), then reactivates (pin returns to LOW).

**Expected behavior**

At startup, the relay should be off (pin HIGH, since the relay is active-low, with initial: true and invert: true).
When clicking the "Reset Relay1" button, the relay should activate temporarily (pin goes LOW for 0.2 seconds, as defined by pulse: {delay: 0.2, active: false}), then return to its initial state (pin HIGH, relay off).
Each subsequent click should repeat this behavior: activate the relay for 0.2 seconds, then deactivate it.

**Screenshots**

![Image](https://github.com/user-attachments/assets/ade6825f-4dcf-4ac7-9369-ceebe0c5c308)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Vivaldi

**PiKVM info:**
Raspberry Pi board version: Raspberry Pi 4
Video capture type: CSI bridge
kvmd 4.52-1
kvmd-fan 0.32-1
kvmd-platform-v2-hdmi-rpi4 4.52-1
kvmd-webterm 0.50-1

 uname -a
Linux pikvm 6.6.45-10-rpi #1 SMP Fri Jan 24 03:51:01 UTC 2025 armv7l GNU/Linux

**Additional context**
The relay is active-low, meaning it activates when the GPIO pin is LOW (0) and deactivates when the pin is HIGH (1). This is why invert: true is used in the configuration.
The issue persists even when using different interface types in the view section (e.g., "Pulse", "Button", or "Click").

Please help me fix the logic, because  I don't wanna keep the relay always on. I want it always off, except when it's doing a pulse.

**Comment by mdevaev** [comment]
Hello. You have a configuration error: `invert: true` is wrong, it should be `inverted: true`.

**Comment by radu-boboc** [comment]
you are correct, now everything works ok.
Thank you!!

**Comment by mdevaev** [comment]
👌

**Comment by anshtiwari314** [comment]
i have the similar issue with GPIO pins if i set mode: output & try to switch the button from web ui it doesn't toggle GPIO mode from HIGH to LOW. 
 
current problem ( GPIO pin output is always HIGH & not changing  )
similar when u do mode: input ( GPIO pin output is always LOW & not changing by clicking the button )

here is my override.yaml 

```
kvmd:
     gpio:
         drivers:
             my_relay:
                 type: gpio
         view:
             header:
                 title: Switches  # The menu title
             table:  # The menu items are rendered in the form of a table of text labels and controls
                 - ["#Generic GPIO leds"]  # Text starting with the sharp symbol will be a label
                 - []  # creates a horizontal separator and starts a new table
                 - ["#Button 1:", button1]  # Text label, one input, one button with text "Click"
                 - ["#Button 2:", button2]
                 - ["#relay3:", relay3 ]
                 - ["#Led4:", led4 ]
         scheme:
             # A certain device sends signals to the RPi and we want the PiKVM to display this as an led
             button1:
                 pin: 5 # GPIO pin number on the RPi
                 mode: output
                 initial: true
                 inverted: true
                 switch: true
                 pulse:
                     delay: 2
                     max_delay: 2
             button2:
                 pin: 6 # GPIO pin number on the RPi
                 mode: output
                 switch: true
             relay3:
                 driver: my_relay
                 pin: 12
                 mode: output
                 initial: null
                 inverted: true
             led4: 
                 pin: 13
                 mode: input
```

i m also sharing output of my http://pikvm_ip/api/gpio


```
{
    "ok": true,
    "result": {
        "model": {
            "scheme": {
                "inputs": {
                    "led4": {
                        "hw": {
                            "driver": "__gpio__",
                            "pin": "13"
                        }
                    }
                },
                "outputs": {
                    "button1": {
                        "hw": {
                            "driver": "__gpio__",
                            "pin": "5"
                        },
                        "pulse": {
                            "delay": 2.0,
                            "max_delay": 2.0,
                            "min_delay": 0.1
                        },
                        "switch": true
                    },
                    "button2": {
                        "hw": {
                            "driver": "__gpio__",
                            "pin": "6"
                        },
                        "pulse": {
                            "delay": 0.1,
                            "max_delay": 0.1,
                            "min_delay": 0.1
                        },
                        "switch": true
                    },
                    "relay3": {
                        "hw": {
                            "driver": "my_relay",
                            "pin": "12"
                        },
                        "pulse": {
                            "delay": 0.1,
                            "max_delay": 0.1,
                            "min_delay": 0.1
                        },
                        "switch": true
                    }
                }
            },
            "view": {
                "header": {
                    "title": [
                        {
                            "text": "Switches",
                            "type": "label"
                        }
                    ]
                },
                "table": [
                    [
                        {
                            "text": "Generic GPIO leds",
                            "type": "label"
                        }
                    ],
                    null,
                    [
                        {
                            "text": "Button 1:",
                            "type": "label"
                        },
                        {
                            "channel": "button1",
                            "confirm": false,
                            "hide": false,
                            "text": "Click",
                            "type": "output"
                        }
                    ],
                    [
                        {
                            "text": "Button 2:",
                            "type": "label"
                        },
                        {
                            "channel": "button2",
                            "confirm": false,
                            "hide": false,
                            "text": "Click",
                            "type": "output"
                        }
                    ],
                    [
                        {
                            "text": "relay3:",
                            "type": "label"
                        },
                        {
                            "channel": "relay3",
                            "confirm": false,
                            "hide": false,
                            "text": "Click",
                            "type": "output"
                        }
                    ],
                    [
                        {
                            "text": "Led4:",
                            "type": "label"
                        },
                        {
                            "channel": "led4",
                            "color": "green",
                            "type": "input"
                        }
                    ]
                ]
            }
        },
        "state": {
            "inputs": {
                "led4": {
                    "online": true,
                    "state": true
                }
            },
            "outputs": {
                "button1": {
                    "busy": false,
                    "online": true,
                    "state": false
                },
                "button2": {
                    "busy": false,
                    "online": true,
                    "state": false
                },
                "relay3": {
                    "busy": false,
                    "online": true,
                    "state": true
                }
            }
        }
    }
}

```

@mdevaev @radu-boboc can u pls guide me what i m doing wrong . Thankyou
