### ISSUE TITLE
what to enter in the override.yaml to make the relay work

### ISSUE THREAD

**Issue by GrafDe** [pikvm/pikvm#294]
i have usb-relay. it is detected as 
```
# lsusb
Bus 001 Device 003: ID 5131:2007 MSR MSR-101U Mini HID magnetic card reader
...
# ls /dev/hid*
/dev/hidraw0
```
to close the relay, I send the command in console
```
printf '\xFF\x55' >/dev/hidraw0
```
1) How i can send a signal to close the relay through web-interface ? what i need write in /etc/kvmd/override.yaml

2) I am currently using a bash script from the console to close this relay. This is inconvenient because i have to open the console. Is there a way to run bash scripts from the web interface, like writing multiple lines to /etc/kvmd/override.yaml?

**Comment by strausmann** [comment]
This works for me, after a long after a long fiddling :-)

```yaml
kvmd:
    gpio:
        drivers:
            relay:
                type: hidrelay
                device: /dev/hidraw0
        scheme:
            relay1:
                driver: relay
                pin: 0
                mode: output
                initial: null
                switch: false
            relay2:
                driver: relay
                pin: 1
                mode: output
                initial: null
                switch: false
            relay3:
                driver: relay
                pin: 2
                mode: output
                initial: null
                switch: false
            relay4:
                driver: relay
                pin: 3
                mode: output
                initial: null
                switch: false
        view:
            header:
               title: "HDMI Switch"
            table:
                - ["#HID Relays /dev/hidraw0"]
                - []
                - ["#Port #1:", "relay1"]
                - ["#Port #2:", "relay2"]
                - ["#Port #3:", "relay3"]
                - ["#Port #4:", "relay4"]
```
