### ISSUE TITLE
Add http requests or mqtt support

### ISSUE THREAD

**Issue by connected201** [pikvm/pikvm#448]
hi, i have loot of relay from sonoff or other vendors, and these relays can be started or stopped with simple http request or publish mqtt topic, with these relay i trigger to start or stop my PC
![image](https://user-images.githubusercontent.com/20506433/132367403-fc59e81a-a28d-4761-be26-67534d931ddb.png)
Sonoff SV

 it's possible to add option in ATX menu option to make http request to relay?

[example](https://github.com/xoseperez/espurna/wiki/RESTAPI)

**Comment by mdevaev** [comment]
We need to write [GPIO](https://github.com/pikvm/pikvm/blob/master/pages/gpio.md) plugin for this. I don't have a device to make and test this.

**Comment by connected201** [comment]
this rellay is triggered via MQTT protocol, no wires! this device have wifi module on board (esp8266)

**Comment by philipforget** [comment]
This one would be really useful for me too, easy to tuck one of these away inside the case near the ATX connectors of the mobo vs running wires back to a central point. 

A board like this is [cheap 4 relay esp32 dev board](https://www.aliexpress.com/item/1005003161500835.html), or maybe even a cheap custom board with optoisolators and atx style connector passthrough could be designed for this purpose.

For the actual actuation, something like mqtt could work with a small broker container running on pikvm (or supply your own). Maybe leveraging something like https://esphome.io/ for building a small firmware and OTA updates etc. I'll investigate this a bit more in the new year too.

**Comment by adamoutler** [comment]
Run Local Script tab would be helpful here.  Some predefined scripts could be activated, scheduled, and based on the output a command could be issued.   With this solution, #448, #460 ... too many to enumerate.  They could be addressed as well.

**Comment by ndng28** [comment]
+1 for this feature request

**Comment by mdevaev** [comment]
There is the CMD plugin to run scripts: https://docs.pikvm.org/gpio/#cmd

**Comment by adamoutler** [comment]
Well, great!  Curl is an option for http requests.

**Comment by Slarag** [comment]
CMD plugin and curl can be used to send out MQTT requests, but is there also an option to get feed back via MQTT? E.g. a relay is set via MQTT (either via a button in the PiKVM frontend or some other device/script interacting with MQTT) and this relay reports back its status via another MQTT topic. I would make sense, that the toggle button then reflects the value that was last reported back.

**Comment by adamoutler** [comment]
Wrap a `netcat -l` in a `while` loop and parse the output?

**Comment by Slarag** [comment]
What about a plugin for MQTT that wraps [asyncio-mqtt](https://pypi.org/project/asyncio-mqtt/)?

I have not really worked with async code yet, so please correct me if I'm getting something wrong about the plugin infrastrucure or other terms. Opinions/ideas/feedback on the idea of such a plugin?

Configuration could look like this:
```
kvmd:
    gpio:
        drivers:
            mqtt:
                type: mqttrelay
                broker: localhost
                port: 1883
                ...
        scheme:
                relay1:
                    driver: mqtt
                    mode: output # Or bidirectional or similar
                    switch: true
                    write_topic: "/relay1/set"
                    # Read topic is the topic where the relay publishes its status when it changes
                    read_topic: "/relay1/value"
                relay2:
                    driver: mqtt
                    mode: output # Or bidirectional or similar
                    switch: true
                    write_topic: "/relay2/set"
                    read_topic: "/relay2/value"
                ...
```
