### ISSUE TITLE
kvmd ignoring keymap configuration

### ISSUE THREAD

**Issue by jnko** [pikvm/pikvm#504]
I've chnaged the keymap to be used in `/etc/kvmd/override.yaml` to 

```
vnc:
    keymap: /usr/share/kvmd/keymaps/de
```
as documented in https://github.com/pikvm/pikvm/blob/master/pages/vnc.md.

Running `kvmd -m` tells that the keyboard should load, but the logs tell me it won't.

`kvmd -m`:
```
...
vnc:
    auth:
        vncauth:
            enabled: false
            file: /etc/kvmd/vncpasswd


    desired_fps: 30
    # keymap: /usr/share/kvmd/keymaps/en-us
    keymap: /usr/share/kvmd/keymaps/de
    kvmd:
        host: localhost
        port: 0
        timeout: 5.0
        # unix: ''
        unix: /run/kvmd/kvmd.sock
...
```

`journalctl -f` :
```
Oct 12 16:03:17 pikvm kvmd[2091]: kvmd.plugins.msd.otg.helpers      INFO --- => Remounting /var/lib/kvmd/msd to RO-mode ...
Oct 12 16:03:17 pikvm kvmd[2091]: kvmd.keyboard.keysym              INFO --- Reading keyboard layout /usr/share/kvmd/keymaps/en-us ...
```

as well as the layout is not `de`
![image](https://user-images.githubusercontent.com/2241599/136963066-ab15e519-9db8-4266-b5e3-180ed94361aa.png)

Btw: Thanks for the fantastic project - I backed my pikvm on Kickstarter
