### ISSUE TITLE
Ethernet-over-USB network speed

### ISSUE THREAD

**Issue by ahmaddxb** [pikvm/pikvm#762]
Why is the ncm drivers upload speed so terrible? Is this normal for other users. 

```
otgnet:
    firewall:
        allow_tcp: [80, 443]
        forward_iface: eth0
    commands:
        post_start_cmd_append:
            - "--dhcp-option=6,1.1.1.1,1.0.0.1"
    iface:
        ip_cmd:
            - /usr/bin/ip
        net: 10.65.0.0/28
```
Tested in windows 10

Driver = rndis
Download 180Mbps Upload 90Mbps

Driver = ncm
Download 300Mbps Upload 5Mbps
