### ISSUE TITLE
HowTo GeekPi 4 channel relay (ATX)

### ISSUE THREAD

**Issue by arch1mede** [pikvm/pikvm#802]
From TheCaptian on discord.

This guide walks you through the steps required to add a GeeekPi 4 channel relay [HAT](https://www.amazon.com/GeeekPi-Raspberry-Expansion-Programming-Programmable/dp/B07Q2P9D7K) allowing ATX power control over each of the four devices attached to your ezcoo hdmi switch. It assumes you have a working and updated installation of v2 software on Pi 4b. The GeeekPi 4ch relay HAT should obviously be installed onto the Pi.

From command line, as root after enabling rw:

Enable i2c:
-    Add this line using: nano /boot/config.txt: 
dtparam=i2c_arm=on
-    Add this line using: nano /etc/modules-load.d/raspberrypi.conf: 
i2c-dev
-    Reboot
-    install i2c-tools: 
pacman -S i2c-tools
-    check install by running: 
i2cdetect -y 1 if you see something like this, continue

     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: 10 -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- 3c -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

Prepare trigger scripts:
-    Create relay directory inside /etc: 
mkdir /etc/relay
-    Create a script inside /etc/relay (example script below). You will need two scripts per channel assuming you’d like both a ‘short’ and ‘long’ press.
nano /etc/relay/ch1s.py, nano /etc/relay/ch1l.py … etc for channels 1 through 4. You should have eight scripts total, check with ls /etc/relay 
-    make each script executable using:
chmod a+x name.py where name.py is replaced with the name of each script

-    Allow default user (kvmd) to execute scripts within gui by adding kvmd user to i2c group:
usermod -a -G i2c kvmd

-    Modify override.yaml file to add functionality to gui (see below for example):
nano /etc/kvmd/override.yaml

-    Connect each relay to the power pins on it’s corresponding machine. I used 24/2 doorbell wire with dupont wires soldered on. The wires should be connected to Normally Open and Common ports, however there’s a discrepancy on the two GeeekPi 4ch HAT’s I’ve seen – the silkscreen print indicating NC/NO is reversed. This is a manufacturing error. If your relay is like mine, you’ll need to connect the wires to the ports labeled NC and COM.
![image](https://user-images.githubusercontent.com/3489071/184152146-00c3acb0-b7e5-4ad1-8aff-b95bfb53b1b4.png)
Ch1 script, for channels 2, 3 and 4 adjust range(1, 2): to range(2, 3):, range(3, 4): and range(4, 5): respectively. Adjust relay contact time by modifying the number in parentheses here t.sleep(0.5). I use 0.5 secs as short press and 6 secs as long press.

```python
#!/usr/bin/env python
#
import time as t
import smbus

DEVICE_BUS = 1
DEVICE_ADDR = 0x10
bus = smbus.SMBus(DEVICE_BUS)

while True:
    try:
        for i in range(1, 2):
            bus.write_byte_data(DEVICE_ADDR, i, 0xFF)
            t.sleep(0.5)
            bus.write_byte_data(DEVICE_ADDR, i, 0x00)
            t.sleep(1)
        break
    except KeyboardInterrupt as e:
        print("Quit the Loop")
quit(1)
````

override.yaml
```yaml
kvmd:
    gpio:
        drivers:
            relay1s:
                type: cmd
                cmd: [/etc/relay/ch1s.py]
            relay1l:
                type: cmd
                cmd: [/etc/relay/ch1l.py]
            relay2s:
                type: cmd
                cmd: [/etc/relay/ch2s.py]
            relay2l:
                type: cmd
                cmd: [/etc/relay/ch2l.py]
            relay3s:
                type: cmd
                cmd: [/etc/relay/ch3s.py]
            relay3l:
                type: cmd
                cmd: [/etc/relay/ch3l.py]
            relay4s:
                type: cmd
                cmd: [/etc/relay/ch4s.py]
            relay4l:
                type: cmd
                cmd: [/etc/relay/ch4l.py]
            ez:
                type: ezcoo
                protocol: 2
                device: /dev/ttyUSB0
        scheme:
            relay1s:
                driver: relay1s
                pin: 0
                mode: output
                switch: false
            relay1l:
                driver: relay1l
                pin: 1
                mode: output
                switch: false
            relay2s:
                driver: relay2s
                pin: 2
                mode: output
                switch: false
            relay2l:
                driver: relay2l
                pin: 3
                mode: output
                switch: false
            relay3s:
                driver: relay3s
                pin: 4
                mode: output
                switch: false
            relay3l:
                driver: relay3l
                pin: 5
                mode: output
                switch: false
            relay4s:
                driver: relay4s
                pin: 6
                mode: output
                switch: false
            relay4l:
                driver: relay4l
                pin: 7
                mode: output
                switch: false
            ch0_led:
                driver: ez
                pin: 0
                mode: input
            ch1_led:
                driver: ez
                pin: 1
                mode: input
            ch2_led:
                driver: ez
                pin: 2
                mode: input
            ch3_led:
                driver: ez
                pin: 3
                mode: input
            ch0_button:
                driver: ez
                pin: 0
                mode: output
                switch: false
            ch1_button:
                driver: ez
                pin: 1
                mode: output
                switch: false
            ch2_button:
                driver: ez
                pin: 2
                mode: output
                switch: false
            ch3_button:
                driver: ez
                pin: 3
                mode: output
                switch: false
        view:
            header:
                title: Source
            table:
                - []
                - ["#Input 1", ch0_led, "ch0_button|Select", "relay1s|Short", "relay1l|Long"]
                - []
                - ["#Input 2", ch1_led, "ch1_button|Select", "relay2s|Short", "relay2l|Long"]
                - []
                - ["#Input 3", ch2_led, "ch2_button|Select", "relay3s|Short", "relay3l|Long"]
                - []
                - ["#Input 4", ch3_led, "ch3_button|Select", "relay4s|Short", "relay4l|Long"]
                - []
```

The case is a modified version of this modular [setup](https://www.thingiverse.com/thing:4399405)
