### ISSUE TITLE
Ability to use LEDs in GPIO title

### ISSUE THREAD

**Issue by ivareri** [pikvm/pikvm#803]
**Is your feature request related to a problem? Please describe.**
I want a way to see GPIO input states at a glance. 

My specific use case is to check which channel is active on a GPIO controlled KVM. 

![image](https://user-images.githubusercontent.com/1616486/184210965-75bca71d-7c2d-4a83-9a25-f65dd8543725.png) 

**Describe the solution you'd like**
An easy way to include LEDs in GPIO title

**Describe alternatives you've considered**
Including HTML in the yaml config

**Additional context**
This config does what I want, but it's a bit messy
```
kvmd:
    gpio:
        scheme:
            PC1:
                mode: input
                pin: 17
            PC2:
                mode: input
                pin: 27
            button1:
                mode: output
                pin: 22
                switch: false
        view:
            header:
                title: 'KVM PC1 <img id="gpio-led-PC1" class="gpio-led inline-lamp-big led-gray" src="/share/svg/led-circle.svg" data-color="green"> PC2 <img id="gpio-led-PC2" class="gpio-led inline-lamp-big led-green" src="/share/svg/led-circle.svg" data-color="green">'
            table:
                - ["#KVM Input selection"]
                - []
                - ["button1|Change"]
```
