### ISSUE TITLE
Better support for removable devices (e.g. USB GPIO boards)

### ISSUE THREAD

**Issue by zappanaut** [pikvm/pikvm#946]
**Is your feature request related to a problem? Please describe.**

I am using a RP2040 as a GPIO extension for ATX control on multiple PCs which is added as a GPIO device in the `override.yaml` file.
Unfortunately a removable device lets kvmd crash if it is not connected or is disconnected during runtime.

**Describe the solution you'd like**

* Prevent kvmd from crashing if a device is not found or is disconnected during runtime.
* Introduce a flag to mark removable devices (removable: yes/no). Provide the ability to visualize this in the frontend, e.g. by using special input pin name like "status".

Suggested example configuration:

```
kvmd:
    gpio:
        drivers:
            atx_port:
                type: gpio
                device: /dev/removable-gpio-extension-device
                removable: yes
        scheme:
            gpio_status_led:
                driver: atx_port
                pin: status
                mode: input
```

**Describe alternatives you've considered**

Sorry, don't know of any alternatives.

**Additional context**

Got a bug report (https://github.com/zappanaut/pikvm-usb-atx-ctrl/issues/1) and thought it better fits here as a feature request.
